state_dic = {
        'AK': 'Alaska',
        'AL': 'Alabama',
        'AR': 'Arkansas',
        'AS': 'American Samoa',
        'AZ': 'Arizona',
        'CA': 'California',
        'CO': 'Colorado',
        'CT': 'Connecticut',
        'DC': 'District of Columbia',
        'DE': 'Delaware',
        'FL': 'Florida',
        'GA': 'Georgia',
        'GU': 'Guam',
        'HI': 'Hawaii',
        'IA': 'Iowa',
        'ID': 'Idaho',
        'IL': 'Illinois',
        'IN': 'Indiana',
        'KS': 'Kansas',
        'KY': 'Kentucky',
        'LA': 'Louisiana',
        'MA': 'Massachusetts',
        'MD': 'Maryland',
        'ME': 'Maine',
        'MI': 'Michigan',
        'MN': 'Minnesota',
        'MO': 'Missouri',
        'MP': 'Northern Mariana Islands',
        'MS': 'Mississippi',
        'MT': 'Montana',
        'NA': 'National',
        'NC': 'North Carolina',
        'ND': 'North Dakota',
        'NE': 'Nebraska',
        'NH': 'New Hampshire',
        'NJ': 'New Jersey',
        'NM': 'New Mexico',
        'NV': 'Nevada',
        'NY': 'New York',
        'OH': 'Ohio',
        'OK': 'Oklahoma',
        'OR': 'Oregon',
        'PA': 'Pennsylvania',
        'PR': 'Puerto Rico',
        'RI': 'Rhode Island',
        'SC': 'South Carolina',
        'SD': 'South Dakota',
        'TN': 'Tennessee',
        'TX': 'Texas',
        'UT': 'Utah',
        'VA': 'Virginia',
        'VI': 'Virgin Islands',
        'VT': 'Vermont',
        'WA': 'Washington',
        'WI': 'Wisconsin',
        'WV': 'West Virginia',
        'WY': 'Wyoming',
        'US': 'USA'
}

dropdown_options=[
    {'label': 'USA', 'value': 'US'},
    {'label': 'Alaska', 'value': 'AK'},
    {'label': 'Alabama', 'value': 'AL'},
    {'label': 'Arkansas', 'value': 'AR'},
    # {'label': 'American Samoa', 'value': 'AS'},
    {'label': 'Arizona', 'value': 'AZ'},
    {'label': 'California', 'value': 'CA'},
    {'label': 'Colorado', 'value': 'CO'},
    {'label': 'Connecticut', 'value': 'CT'},
    {'label': 'District of Columbia', 'value': 'DC'},
    {'label': 'Delaware', 'value': 'DE'},
    {'label': 'Florida', 'value': 'FL'},
    {'label': 'Georgia', 'value': 'GA'},
    # {'label': 'Guam', 'value': 'GU'},
    {'label': 'Hawaii', 'value': 'HI'},
    {'label': 'Iowa', 'value': 'IA'},
    {'label': 'Idaho', 'value': 'ID'},
    {'label': 'Illinois', 'value': 'IL'},
    {'label': 'Indiana', 'value': 'IN'},
    {'label': 'Kansas', 'value': 'KS'},
    {'label': 'Kentucky', 'value': 'KY'},
    {'label': 'Louisiana', 'value': 'LA'},
    {'label': 'Massachusetts', 'value': 'MA'},
    {'label': 'Maryland', 'value': 'MD'},
    {'label': 'Maine', 'value': 'ME'},
    {'label': 'Michigan', 'value': 'MI'},
    {'label': 'Minnesota', 'value': 'MN'},
    {'label': 'Missouri', 'value': 'MO'},
    # {'label': 'Northern Mariana Islands', 'value': 'MP'},
    {'label': 'Mississippi', 'value': 'MS'},
    {'label': 'Montana', 'value': 'MT'},
    # {'label': 'National', 'value': 'NA'},
    {'label': 'North Carolina', 'value': 'NC'},
    {'label': 'North Dakota', 'value': 'ND'},
    {'label': 'Nebraska', 'value': 'NE'},
    {'label': 'New Hampshire', 'value': 'NH'},
    {'label': 'New Jersey', 'value': 'NJ'},
    {'label': 'New Mexico', 'value': 'NM'},
    {'label': 'Nevada', 'value': 'NV'},
    {'label': 'New York', 'value': 'NY'},
    {'label': 'Ohio', 'value': 'OH'},
    {'label': 'Oklahoma', 'value': 'OK'},
    {'label': 'Oregon', 'value': 'OR'},
    {'label': 'Pennsylvania', 'value': 'PA'},
    # {'label': 'Puerto Rico', 'value': 'PR'},
    {'label': 'Rhode Island', 'value': 'RI'},
    {'label': 'South Carolina', 'value': 'SC'},
    {'label': 'South Dakota', 'value': 'SD'},
    {'label': 'Tennessee', 'value': 'TN'},
    {'label': 'Texas', 'value': 'TX'},
    {'label': 'Utah', 'value': 'UT'},
    {'label': 'Virginia', 'value': 'VA'},
    # {'label': 'Virgin Islands', 'value': 'VI'},
    {'label': 'Vermont', 'value': 'VT'},
    {'label': 'Washington', 'value': 'WA'},
    {'label': 'Wisconsin', 'value': 'WI'},
    {'label': 'West Virginia', 'value': 'WV'},
    {'label': 'Wyoming', 'value': 'WY'}
]